// <auto-generated />
namespace ProyectoPograAvanzada.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RegistroActualizado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegistroActualizado));
        
        string IMigrationMetadata.Id
        {
            get { return "202503260700383_RegistroActualizado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
