// <auto-generated />
namespace ProyectoPograAvanzada.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Resenas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Resenas));
        
        string IMigrationMetadata.Id
        {
            get { return "202503281551073_Resenas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
